version: '3'
services:
  database:
    image: mongo
    restart: always
    container_name: 'dx-logger-db'
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: dx-logger
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example